# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pb2.securedexchange_pb2 as securedexchange__pb2


class ExchangeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendModel = channel.stream_unary(
                '/securedexchange.Exchange/SendModel',
                request_serializer=securedexchange__pb2.Model.SerializeToString,
                response_deserializer=securedexchange__pb2.SimpleReply.FromString,
                )
        self.SendData = channel.stream_unary(
                '/securedexchange.Exchange/SendData',
                request_serializer=securedexchange__pb2.Data.SerializeToString,
                response_deserializer=securedexchange__pb2.ModelResult.FromString,
                )


class ExchangeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendModel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendModel': grpc.stream_unary_rpc_method_handler(
                    servicer.SendModel,
                    request_deserializer=securedexchange__pb2.Model.FromString,
                    response_serializer=securedexchange__pb2.SimpleReply.SerializeToString,
            ),
            'SendData': grpc.stream_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=securedexchange__pb2.Data.FromString,
                    response_serializer=securedexchange__pb2.ModelResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'securedexchange.Exchange', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Exchange(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/securedexchange.Exchange/SendModel',
            securedexchange__pb2.Model.SerializeToString,
            securedexchange__pb2.SimpleReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/securedexchange.Exchange/SendData',
            securedexchange__pb2.Data.SerializeToString,
            securedexchange__pb2.ModelResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
