version: 2

submodules:
  include: all

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt_packages:
  - cmake
  jobs:
    pre_create_environment: 
    - cp examples/*/*.ipynb docs
    - bash .github/scripts/cleanup_notebook_name.sh
    post_install:
    - bash docs/generate_api_reference.sh

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true

python:
    install:
    - requirements: docs/requirements.txt
    - requirements: client/requirements.txt
    - method: pip
      path: client
