pip install pdoc3
pdoc --html --skip-errors -o docs/resources client/blindai
sed -i '/<p>Generated by <a href="https:\/\/pdoc3.github.io\/pdoc" title="pdoc: Python API documentation generator"><cite>pdoc<\/cite> 0.10.0<\/a>.<\/p>/d' docs/resources/blindai/*.html docs/resources/blindai/*/*.html